-- select database
use DQL_DATABASE;
SELECT * FROM EMPLOYEES;

-- FIND THE TOTAL EMPLOYEES IN EMPLOYEES TABLE
SELECT COUNT(*) FROM EMPLOYEES;

-- FIND TOTAL SALARY COMPANY SPEND ON EMPLOYEES
SELECT SUM(SALARY) FROM EMPLOYEES;

-- FIND AVERAGE SALARY OF TOTAL EMPLOYEES
SELECT AVG(SALARY) FROM EMPLOYEES;

-- FIND THE MAXIMUM SALARY COMPANY PROVIDING
SELECT MAX(SALARY) FROM EMPLOYEES;

-- FIND MINIMUM SALARY IN EMPLOYEES TABLE
SELECT MIN(SALARY) FROM EMPLOYEES;

-- find total salary spending on department_id 50
SELECT SUM(SALARY)  FROM EMPLOYEES WHERE DEPARTMENT_ID = 50;

-- find total employees present under the 101 manager_id
SELECT COUNT(*)  AS TOTAL_EMPLOYEES FROM EMPLOYEES WHERE MANAGER_ID = 101;

-- FIND TOTAL EMPLOYEES IN EACH DEPARTMENT
SELECT DEPARTMENT_ID, COUNT(*) AS TOTAL_EMPLOYEES FROM EMPLOYEES GROUP BY DEPARTMENT_ID;

-- FIND TOTAL SALARIES, MAXIMUM_SALARY AND MINIMUM SALARY IN EACH MANAGER
SELECT MANAGER_ID, COUNT(*), MAX(SALARY), MIN(SALARY) FROM EMPLOYEES GROUP BY MANAGER_ID;

-- RETURN TOTAL EMPLOYEES COUNT AS MANAGER ID AND DEPARTMENT ID AND SORT BY
		-- TOTAL EMPLOYEES IN DESCENDING ORDER
SELECT MANAGER_ID, DEPARTMENT_ID, COUNT(*) AS TOTAL_EMPLOYEES FROM EMPLOYEES GROUP BY MANAGER_ID, DEPARTMENT_ID ORDER BY TOTAL_EMPLOYEES DESC;
        
-- FIND THE DEPARTMENTS WHERE TOTAL SALARY IS MORETHAN 35000
SELECT DEPARTMENT_ID, COUNT(SALARY) FROM EMPLOYEES WHERE SALARY > 35000 GROUP BY DEPARTMENT_ID;

-- FIND EMPLOYEES COUNT WHERE SALARY IS MORETHAN 10000 AS PER DEPARTMENT
SELECT DEPARTMENT_ID, COUNT(*) AS TOTAL_EMPLOYEES FROM EMPLOYEES WHERE SALARY > 10000 GROUP BY DEPARTMENT_ID;

-- FIND DEPARTMENTS WHERE AVERAGE SALARY OF EACH GROUP MORETHAN 10000 AS WELL AS EACH EMPLOYEE SALARY IS LESSTHAN 10000
SELECT DEPARTMENT_ID, AVG(SALARY) FROM EMPLOYEES
WHERE SALARY < 10000 
GROUP BY DEPARTMENT_ID 
HAVING AVG(SALARY) > 7000;