-- Creating the database
create database student;
use student;

-- CREATING THE TABLES
CREATE TABLE USERS(
STD_ID INT,
STD_NAME VARCHAR(30),
STD_AGE INT,
STD_DEPT VARCHAR(30),
STD_EMAIL VARCHAR(100)
);

-- ALTERING THE TABLE
-- ADDING A NEW COLUMN TO AN EXISTING COLUMN
ALTER TABLE USERS ADD CITY VARCHAR(50);



-- INSERTING THE RECORDS
INSERT INTO USERS (STD_ID, STD_NAME, STD_AGE, STD_DEPT, STD_EMAIL, CITY)
VALUES(1, "PINKY", 18, "CSE", "PINKY@EMAIL.COM", "HYDERABAD"),
(2, "PONKY", 20, "IT", "PONKY@GMAIL.COM", "VIZAG"),
(3, "DARLING", 22, "ECE", "DARLING@GMAIL.COM", "GUNTUR"),
(4, "BABY", 24, "EEE", "BABY@GMAIL.COM", "VIJAYAWADA");

SELECT * FROM USERS;

-- UPDATING THE STUDENTS AGE
UPDATE USERS 
SET STD_AGE = 23
WHERE STD_ID = 1;
set sql_safe_updates = 0;

-- DROP  THE COLUMN NAME
ALTER TABLE USERS DROP COLUMN CITY;

-- RENAMING THE TABLE
RENAME TABLE USERS TO STUDENT_INFO;

-- DELETING A ROW FROM A TABLE
DELETE FROM STUDENT_INFO WHERE STD_ID = 1;

SELECT * FROM STUDENT_INFO;

-- TRUNVATE THE TABLE
TRUNCATE STUDENT_INFO;
