use DQL_DATABASE;
SELECT * FROM EMPLOYEES;

-- return current time, date and timestamp
SELECT CURTIME(), CURDATE(), NOW();
SELECT CURRENT_TIME(), CURRENT_DATE(), CURRENT_TIMESTAMP();

-- RETURN YEAR, MONTH, DAY FROM CURRENT DATE
SELECT YEAR(CURDATE()), MONTH(CURDATE()), DAY(CURDATE());

-- RETURN HOURS, MINUTES, SECONDS FROM CURRENT TIME STAMP
SELECT HOUR(CURRENT_TIMESTAMP) AS hours, MINUTE(CURRENT_TIMESTAMP) AS minutes, SECOND(CURRENT_TIMESTAMP) AS seconds;

-- RETURN CURRENT QUARTER AND WEEK
SELECT QUARTER(CURRENT_DATE) AS current_quarter, WEEK(CURRENT_DATE) AS current_week;

-- FROM EMPLOYEES TABLE HIREDATE FORMAT CHANGE TO 10/12/2025,
SELECT HIRE_DATE, DATE_FORMAT(STR_TO_DATE(HIRE_DATE, '%d-%b-%Y'), '%d/%m/%Y') from employees;

-- FIND TOTAL EMPLOYEES COUNT RELATED TO DAY OF HIREDATE
select  day(STR_TO_DATE(HIRE_DATE, '%d-%b-%Y')), COUNT(*) FROM EMPLOYEES
GROUP BY DAY(STR_TO_DATE(HIRE_DATE, '%d-%b-%Y'));

-- RETURN TOTAL_HIRE_MONTH_SALARY AS SUM OF  SALARY  AS PER THE MONTH OF HIREDATE AND SORT BY TOTAL_HIRE_MONTH_SALARY
SELECT MONTH(STR_TO_DATE(HIRE_DATE, '%d-%b-%Y')),
SUM(SALARY) AS TOTAL_HIRE_MONTH_SALARY 
FROM EMPLOYEES 
GROUP BY MONTH(STR_TO_DATE(HIRE_DATE, '%d-%b-%Y'))
ORDER BY TOTAL_HIRE_MONTH_SALARY DESC;