use university;

--  creating student table
CREATE TABLE STUDENT (
	ID INT NOT NULL,
    NAME VARCHAR(50) NOT NULL,
    AGE TINYINT,
    CLASS TINYINT,
    PRIMARY KEY(ID)
);

-- INSERT DATA INTO STUDENTS TABLE
INSERT INTO STUDENT(ID, NAME, AGE, CLASS)
VALUES(1, 'RAVI', 15, 10),
		(2, 'SIRI', 14, 9),
        (3, 'PRASSU', 14, 8),
        (4, 'UMA', 15, 9),
        (5, 'SAILU', 13, 8);
SELECT * FROM STUDENT;

-- CREATING CHILD TABLE
CREATE TABLE MARKS(
STD_ID INT NOT NULL,
COURSE_ID INT NOT NULL,
S1_MARKS TINYINT,
S2_MARKS TINYINT,
S3_MARKS TINYINT,
PERCENTAGE DECIMAL(4, 2) GENERATED ALWAYS AS  (((S1_MARKS + S2_MARKS + S3_MARKS)/300) * 100) STORED,
PRIMARY KEY(COURSE_ID),
FOREIGN KEY(STD_ID) REFERENCES STUDENT(ID)
);

-- INSERT SOME DATA IN CHILD TABLE
INSERT INTO MARKS(STD_ID, COURSE_ID, S1_MARKS, S2_MARKS, S3_MARKS)
VALUES (1, 1001, 86, 89, 57),
		(2, 1002, 68, 88, 95),
        (3, 1005, 75, 85, 66);
SELECT * FROM MARKS;

-- INSERT ONE ID RECORD THAT WAS NOT PRESENT IN PARENT TABLE
INSERT INTO MARKS(STD_ID, COURSE_ID, S1_MARKS, S2_MARKS, S3_MARKS)
VALUES (10, 1010, 86, 89, 57);

-- UPDATE ONE RECORD THAT WAS PRESENT IN CHILD TABLE
UPDATE STUDENT SET ID = 101
WHERE ID = 1;

-- UPDATE ONE RECORD THAT WAS PRESENT IN CHILD TABLE
UPDATE STUDENT SET ID = 104
WHERE ID = 4;

SELECT * FROM STUDENT;
SELECT * FROM MARKS;

-- CHECK INTEGRITY
-- DROP CHILD TABLE
DROP TABLE MARKS;

-- CREATING CHILD TABLE
CREATE TABLE MARKS(
STD_ID INT NOT NULL,
COURSE_ID INT NOT NULL,
S1_MARKS TINYINT,
S2_MARKS TINYINT,
S3_MARKS TINYINT,
PERCENTAGE DECIMAL(4, 2) GENERATED ALWAYS AS  (((S1_MARKS + S2_MARKS + S3_MARKS)/300) * 100) STORED,
PRIMARY KEY(COURSE_ID),
FOREIGN KEY(STD_ID) REFERENCES STUDENT(ID)
ON UPDATE CASCADE
ON DELETE CASCADE
);
INSERT INTO MARKS(STD_ID, COURSE_ID, S1_MARKS, S2_MARKS, S3_MARKS)
VALUES (1, 1001, 86, 89, 57),
		(2, 1002, 68, 88, 95),
        (104, 1005, 75, 85, 66);

-- UPDATE ONE RECORD THAT WAS PRESENT IN CHILD TABLE
UPDATE STUDENT SET ID = 101
WHERE ID = 1;

SELECT * FROM STUDENT;
SELECT * FROM MARKS;

-- DELETE ONE RECORD THAT IS PRESENT IN CHILD TABLE
DELETE FROM STUDENT WHERE ID = 2;


-- INNERJOIN
SELECT STUDENT.ID, STUDENT.NAME, STUDENT.CLASS, MARKS.PERCENTAGE FROM STUDENT
INNER JOIN MARKS
ON STUDENT.ID = MARKS.STD_ID;

-- EQUI JOIN
SELECT STUDENT.ID, STUDENT.NAME, STUDENT.CLASS, MARKS.PERCENTAGE FROM STUDENT, MARKS
WHERE STUDENT.ID = MARKS.STD_ID;

-- NON EQUI JOIN
SELECT STUDENT.ID, STUDENT.NAME, STUDENT.CLASS, MARKS.PERCENTAGE FROM STUDENT, MARKS
WHERE STUDENT.ID IN (1,2,5);

-- CHANGE COLUMN NAME STD_ID TO ID
ALTER TABLE MARKS RENAME COLUMN STD_ID TO ID;

SELECT STUDENT.ID, STUDENT.NAME, STUDENT.CLASS, MARKS.PERCENTAGE 
FROM STUDENT
NATURAL JOIN MARKS;

SELECT * FROM STUDENT;
SELECT * FROM MARKS;
